---
title: "Capitulo de Larry y Ken"
output: html_notebook
---
```{r}
UVGSDTcrit <- function(dp, sig, logbeta){ 
  TwoSigSq <- 2 * sig^2
  minLam <- optimize(function(X, dp, sig)
  -((1 - sig^2) * X^2 - 2 * dp * X +
      dp^2 + TwoSigSq * log(sig))/TwoSigSq, c(-10, 10), 
      dp = dp, sig = sig)$objective
  if (logbeta < minLam) warning("complex roots") 
  cf <- -c(dp^2 + TwoSigSq * log(sig) + logbeta *
             TwoSigSq, 
           -2 * dp, 1 - sig^2)/TwoSigSq 
  proot <- polyroot(cf) 
  sort(Re(proot))
}



rUVGSDTcrit <- function(dp, sig, logbeta, Nn, Ns = NULL, aggregate = TRUE){
  if (is.null(Ns)) Ns <- Nn
  crit <- UVGSDTcrit(dp, sig, logbeta)
  Rn <- rnorm(Nn)
  Rs <- rnorm(Ns, dp, sig)
  RespN <- (Rn < crit[1]) | (Rn > crit[2]) 
  RespS <- (Rs < crit[1]) | (Rs > crit[2]) 
  if (aggregate)
    c(pFA = sum(RespN)/Nn, pH = sum(RespS)/Ns) else 
      data.frame(Resp = c(RespN, RespS),
                 Stim = factor(rep(0:1, c(Nn, Ns))))
}

rUVGSDTcritmio <- function(dp, sig, logbeta, Nn, Ns = NULL, aggregate = TRUE){
  if (is.null(Ns)) Ns <- Nn
  crit <- UVGSDTcrit(dp, sig, logbeta)
  Rn <- rnorm(Nn)
  Rs <- rnorm(Ns, dp, sig)
  RespN <- (Rn < crit[1]) | (Rn > crit[2]) 
  RespS <- (Rs < crit[1]) | (Rs > crit[2]) 
  if (aggregate) {
    c(pFA = sum(RespN)/Nn, pH = sum(RespS)/Ns) %>% 
      as.list() %>% as_tibble()
    }
  else 
      data.frame(Resp = c(RespN, RespS),
                 Stim = factor(rep(0:1, c(Nn, Ns)))) %>% 
    mutate(crit1 = crit[1], crit2 = crit[2])
}

rUVGSDTcritmio_s <- function(dp, sig, logbeta, Nn, Ns = NULL, aggregate = TRUE){
  if (is.null(Ns)) Ns <- Nn
  crit <- UVGSDTcrit(dp, sig, logbeta)
  Rn <- rnorm(Nn)
  Rs <- rnorm(Ns, dp, sig)
  RespN <- (Rn > crit[2]) 
  RespS <- (Rs > crit[2]) 
  if (aggregate) {
    c(pFA = sum(RespN)/Nn, pH = sum(RespS)/Ns) %>% 
      as.list() %>% as_tibble()
    }
  else 
      data.frame(Resp = c(RespN, RespS),
                 Stim = factor(rep(0:1, c(Nn, Ns)))) %>% 
    mutate(crit1 = crit[1], crit2 = crit[2])
}

lUVG <- function(p, d) { #p <-c(dp, sig, logbeta_1,_2, ...,_n)
  sig <- p[2]
  print(length(p[-(1:2)]))
  print(levels(d[[3]]))
        
  if (length(p[-(1:2)]) != length(levels(d[[3]])))
    stop("Number of initial estimates of log beta not equal to number of levels of conditions in the data!")
  Pr <- sapply(p[-(1:2)], function(lb, pr) { 
    crit <- UVGSDTcrit(pr[1], sig, lb)
    1 - c(diff(pnorm(crit)),
          diff(pnorm(crit, pr[1], pr[2]))) 
    }, pr = c(p[1], sig))
  print(Pr)
  ll <- sapply(seq_along(levels(d[[3]])), function(Cd)
  {
    with(subset(d, Cond == levels(d$Cond)[Cd]), 
         ifelse(Stim == "1",
                Resp * log(Pr[2, Cd]) +
                  (1 - Resp) * log(1 - Pr[2, Cd]), 
                Resp * log(Pr[1, Cd]) +
                  (1 - Resp) * log(1 - Pr[1, Cd])
         ))
  })
  -sum(unlist(ll))
}

```

```{r}
dprime <- 1
sigma <- 3
lb <- 0

optimal_crit <- UVGSDTcrit(dprime, sigma, lb)

x <-  seq(-5, 5, .1)

dist_dat <- tibble(x) %>% 
  mutate(f_s = dnorm(x, dprime, sigma),
         f_n = dnorm(x, 0, 1)) 

segment_noise <- tibble(x = 0, xend = 0, y = 0, yend = dnorm(0, 0, 1))
segment_signal <- tibble(x = dprime, xend = dprime, y = 0, yend = dnorm(dprime, dprime, sigma))

p <- dist_dat %>% 
  ggplot() +
  geom_line(aes(x = x, y = f_s, lty = "signal")) +
  geom_line(aes(x = x, y = f_n, lty = "noise")) +
  geom_segment(data = segment_noise, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_segment(data = segment_signal, aes(x = x, y = y, xend = xend, yend = yend), lty = 2) +
  geom_vline(xintercept = optimal_crit) +
  geom_vline(xintercept = 0.5*dprime, color = "blue") +
  labs(y = "f")
p

```

```{r}
sim <- rUVGSDTcritmio(dprime, sigma, 0, 1000, aggregate = TRUE)
```

```{r}
sim <- tibble(lb = c(0, seq(-.855, 3, .1 ))) %>% 
  group_by(lb) %>% 
  summarise(rUVGSDTcritmio(dprime, sigma, lb, 10000, aggregate = TRUE)) %>% 
  mutate(pM = 1 - pH,
           pCR = 1 - pFA, 
           pCORRECT = .5 *(pH + pCR),
         zFA = qnorm(pFA), 
         zH = qnorm(pH))

sim_s <- tibble(lb = c(0, seq(-.855, 3, .1 ))) %>% 
  group_by(lb) %>% 
  summarise(rUVGSDTcritmio_s(dprime, sigma, lb, 10000, aggregate = TRUE)) %>%
  mutate(pM = 1 - pH,
         pCR = 1 - pFA, 
         pCORRECT = .5 *(pH + pCR), 
         zFA = qnorm(pFA), 
         zH = qnorm(pH))
  
  
optimal_sensory <- sim_s %>% 
  ungroup() %>% 
  filter(pCORRECT == max(pCORRECT))

optimal_sensory_equal_vari <- -0.5*(qnorm(optimal_sensory$pH) + qnorm(optimal_sensory$pFA))
  
sim %>% 
  ggplot(aes(x = pFA, y = pH)) +
  geom_abline(color = "grey") +
  geom_line() +
  geom_line(aes(x =pFA, y = pCORRECT), lty = 2) +
  geom_line(data = sim_s, aes(x =pFA, y = pCORRECT), lty = 2, color = "blue") +
  geom_line(data = sim_s, color = "blue") +
  geom_point(data = sim %>% filter(lb == 0)) +
 geom_point(data = optimal_sensory, color = "blue") +
  xlim(0, 1) +
  ylim(0, 1) +
  coord_equal()
```

```{r}
dist_dat %>% 
  ggplot() +
  geom_line(aes(x = x, y = f_s, lty = "signal")) +
  geom_line(aes(x = x, y = f_n, lty = "noise")) +
  geom_segment(data = segment_noise, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_segment(data = segment_signal, aes(x = x, y = y, xend = xend, yend = yend), lty = 2) +
  geom_vline(xintercept = optimal_sensory_equal_vari, color = "green") +
  geom_vline(xintercept = optimal_crit) +
  geom_vline(xintercept = -qnorm(optimal_sensory$pFA), color = "red") +
  geom_vline(xintercept = 0.5*dprime, color = "blue") +
  labs(y = "f")

```

```{r}
sim %>% 
  ggplot(aes(x = zFA, y = zH)) +
  geom_abline(color = "grey") +
  geom_line() +
  geom_line(data = sim_s, color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "grey") +
  coord_equal()
```
```{r}
lm(zH~zFA, data = sim)
```
```{r}
lm(zH~zFA, data = sim_s)
```


```{r}
dp <- 1
sig <- 1.5
N <- 50000
lb <- c(1.5, 1)

UVGsim.df <- do.call(rbind, lapply(lb, function(LB) 
  rUVGSDTcrit(dp, sig, LB, N, agg = FALSE)))

UVGsim.df$Cond <- factor(rep(paste("C", seq(length(lb)),sep = ""), each = 2 * N))


minLam <- optimize(function(X, dp, sig) 
  -((1 - sig^2) * X^2 - 2 * dp * X +
      dp^2 + 2 * sig^2 * log(sig))/(2 * sig^2),
  c(-20, 20), dp = dp, sig = sig)$objective

UVG.opt <- optim(c(1.1, 1.6, 1.4, 1.1), lUVG,
                 d = UVGsim.df,
                 method = "L-BFGS-B", hessian = TRUE, 
                 lower = c(0, 1, rep(minLam, length(lb))))

est <- UVG.opt$par
names(est) <- c("dprime", "sigma",paste("log beta", seq(length(lb)), sep = ""))
est
```
```{r}
my_function <- function() {
dp <- 1
sig <- 1.5
N <- 50000
lb <- c(1.5, 1)

UVGsim.df <- do.call(rbind, lapply(lb, function(LB) 
  rUVGSDTcrit(dp, sig, LB, N, agg = FALSE)))

UVGsim.df$Cond <- factor(rep(paste("C", seq(length(lb)),sep = ""), each = 2 * N))


minLam <- optimize(function(X, dp, sig) 
  -((1 - sig^2) * X^2 - 2 * dp * X +
      dp^2 + 2 * sig^2 * log(sig))/(2 * sig^2),
  c(-20, 20), dp = dp, sig = sig)$objective

UVG.opt <- optim(c(1.1, 1.6, 1.4, 1.1), lUVG,
                 d = UVGsim.df,
                 method = "L-BFGS-B", hessian = TRUE, 
                 lower = c(0, 1, rep(minLam, length(lb))))

est <- UVG.opt$par
names(est) <- c("dprime", "sigma",paste("log beta", seq(length(lb)), sep = ""))
est %>% as.list() %>% as_tibble()
}

xx <- tibble(sample = 1:30) %>% 
  group_by(sample) %>% 
  summarise(my_function())
```
```{r}
xx %>% 
  summarise(across(everything(), mean))
```

```{r}
dp <- 1
sig <- 1.5
N <- 50000
lb <- c(1.5, 1)

UVGsim.df <- do.call(rbind, lapply(lb, function(LB) 
  rUVGSDTcrit(dp, sig, LB, N, agg = FALSE)))

fit_sdt_conf <- function(.dat) {


.dat$Cond <- factor(rep(paste("C", seq(length(lb)),sep = ""), each = 2 * N))


minLam <- optimize(function(X, dp, sig) 
  -((1 - sig^2) * X^2 - 2 * dp * X +
      dp^2 + 2 * sig^2 * log(sig))/(2 * sig^2),
  c(-20, 20), dp = dp, sig = sig)$objective

UVG.opt <- optim(c(1.1, 1.6, 1.4, 1.1), lUVG,
                 d = .dat,
                 method = "L-BFGS-B", hessian = TRUE, 
                 lower = c(0, 1, rep(minLam, length(lb))))

est <- UVG.opt$par
names(est) <- c("dprime", "sigma",paste("log beta", seq(length(lb)), sep = ""))

est %>% as.list() %>% as_tibble()
}

fit_sdt_conf(UVGsim.df)
```

