---
title: "Capitulo de Larry y Ken"
output: html_notebook
---
```{r}
UVGSDTcrit <- function(dp, sig, logbeta){ 
  TwoSigSq <- 2 * sig^2
  minLam <- optimize(function(X, dp, sig)
  -((1 - sig^2) * X^2 - 2 * dp * X +
      dp^2 + TwoSigSq * log(sig))/TwoSigSq, c(-10, 10), 
      dp = dp, sig = sig)$objective
  if (logbeta < minLam) warning("complex roots") 
  cf <- -c(dp^2 + TwoSigSq * log(sig) + logbeta *
             TwoSigSq, 
           -2 * dp, 1 - sig^2)/TwoSigSq 
  proot <- polyroot(cf) 
  sort(Re(proot))
}



rUVGSDTcrit <- function(dp, sig, logbeta, Nn, Ns = NULL, aggregate = TRUE){
  if (is.null(Ns)) Ns <- Nn
  crit <- UVGSDTcrit(dp, sig, logbeta)
  Rn <- rnorm(Nn)
  Rs <- rnorm(Ns, dp, sig)
  RespN <- (Rn < crit[1]) | (Rn > crit[2]) 
  RespS <- (Rs < crit[1]) | (Rs > crit[2]) 
  if (aggregate)
    c(pFA = sum(RespN)/Nn, pH = sum(RespS)/Ns) else 
      data.frame(Resp = c(RespN, RespS),
                 Stim = factor(rep(0:1, c(Nn, Ns))))
}

rUVGSDTcritmio <- function(dp, sig, logbeta, Nn, Ns = NULL, aggregate = TRUE){
  if (is.null(Ns)) Ns <- Nn
  crit <- UVGSDTcrit(dp, sig, logbeta)
  Rn <- rnorm(Nn)
  Rs <- rnorm(Ns, dp, sig)
  RespN <- (Rn < crit[1]) | (Rn > crit[2]) 
  RespS <- (Rs < crit[1]) | (Rs > crit[2]) 
  if (aggregate) {
    c(pFA = sum(RespN)/Nn, pH = sum(RespS)/Ns) %>% 
      as.list() %>% as_tibble()
    }
  else 
      data.frame(Resp = c(RespN, RespS),
                 Stim = factor(rep(0:1, c(Nn, Ns)))) %>% 
    mutate(crit1 = crit[1], crit2 = crit[2])
}

rUVGSDTcritmio_s <- function(dp, sig, logbeta, Nn, Ns = NULL, aggregate = TRUE){
  if (is.null(Ns)) Ns <- Nn
  crit <- UVGSDTcrit(dp, sig, logbeta)
  Rn <- rnorm(Nn)
  Rs <- rnorm(Ns, dp, sig)
  RespN <- (Rn > crit[2]) 
  RespS <- (Rs > crit[2]) 
  if (aggregate) {
    c(pFA = sum(RespN)/Nn, pH = sum(RespS)/Ns) %>% 
      as.list() %>% as_tibble()
    }
  else 
      data.frame(Resp = c(RespN, RespS),
                 Stim = factor(rep(0:1, c(Nn, Ns)))) %>% 
    mutate(crit1 = crit[1], crit2 = crit[2])
}

```

```{r}
dprime <- .5
sigma <- 2
lb <- 0

optimal_crit <- UVGSDTcrit(dprime, sigma, lb)

x <-  seq(-5, 5, .1)

dist_dat <- tibble(x) %>% 
  mutate(f_s = dnorm(x, dprime, sigma),
         f_n = dnorm(x, 0, 1)) 

segment_noise <- tibble(x = 0, xend = 0, y = 0, yend = dnorm(0, 0, 1))
segment_signal <- tibble(x = dprime, xend = dprime, y = 0, yend = dnorm(dprime, dprime, sigma))

p <- dist_dat %>% 
  ggplot() +
  geom_line(aes(x = x, y = f_s, lty = "signal")) +
  geom_line(aes(x = x, y = f_n, lty = "noise")) +
  geom_segment(data = segment_noise, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_segment(data = segment_signal, aes(x = x, y = y, xend = xend, yend = yend), lty = 2) +
  geom_vline(xintercept = optimal_crit) +
  geom_vline(xintercept = 0.5*dprime, color = "blue") +
  labs(y = "f")
p

```

```{r}
sim <- rUVGSDTcritmio(dprime, sigma, 0, 1000, aggregate = TRUE)
```

```{r}
sim <- tibble(lb = c(0, seq(-.49, 6, .1 ))) %>% 
  group_by(lb) %>% 
  summarise(rUVGSDTcritmio(dprime, sigma, lb, 10000, aggregate = TRUE)) %>% 
  mutate(pM = 1 - pH,
           pCR = 1 - pFA, 
           pCORRECT = .5 *(pH + pCR),
         zFA = qnorm(pFA), 
         zH = qnorm(pH))

sim_s <- tibble(lb = c(0, seq(-.49, 6, .1 ))) %>% 
  group_by(lb) %>% 
  summarise(rUVGSDTcritmio_s(dprime, sigma, lb, 10000, aggregate = TRUE)) %>%
  mutate(pM = 1 - pH,
         pCR = 1 - pFA, 
         pCORRECT = .5 *(pH + pCR), 
         zFA = qnorm(pFA), 
         zH = qnorm(pH))
  
  
optimal_sensory <- sim_s %>% 
  ungroup() %>% 
  filter(pCORRECT == max(pCORRECT))
  
sim %>% 
  ggplot(aes(x = pFA, y = pH)) +
  geom_abline(color = "grey") +
  geom_line() +
  geom_line(aes(x =pFA, y = pCORRECT), lty = 2) +
  geom_line(data = sim_s, aes(x =pFA, y = pCORRECT), lty = 2, color = "blue") +
  geom_line(data = sim_s, color = "blue") +
  geom_point(data = sim %>% filter(lb == 0)) +
 geom_point(data = optimal_sensory, color = "blue") +
  xlim(0, 1) +
  ylim(0, 1) +
  coord_equal()
```

```{r}
dist_dat %>% 
  ggplot() +
  geom_line(aes(x = x, y = f_s, lty = "signal")) +
  geom_line(aes(x = x, y = f_n, lty = "noise")) +
  geom_segment(data = segment_noise, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_segment(data = segment_signal, aes(x = x, y = y, xend = xend, yend = yend), lty = 2) +
  geom_vline(xintercept = optimal_crit) +
  geom_vline(xintercept = -qnorm(optimal_sensory$pFA), color = "red") +
  geom_vline(xintercept = 0.5*dprime, color = "blue") +
  labs(y = "f")

```

```{r}
sim %>% 
  ggplot(aes(x = zFA, y = zH)) +
  geom_abline(color = "grey") +
  geom_line() +
  geom_line(data = sim_s, color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "grey") +
  coord_equal()
```

