---
title: "glmhmm metacognition confidence"
output: html_notebook
---


```{r}
library(reticulate)
use_condaenv("glmhmm")

source_python("python/glm_hmm.py")
```

```{python}
import numpy as np
import numpy.random as npr
import matplotlib.pyplot as plt
import ssm 
```

```{r}
library(tidyverse)
library(broom)
library(dplyr)
library(R.matlab)
library(cowplot)
library(flexplot)
library(lmtest)
library(car)

list.files("R", full.names = TRUE) |> 
  walk(source)
```

```{r}
options(scipen = 10000000)
```

```{r}
load("RData/m1_conf_post_wins.RData")
load("RData/m2_conf_post_wins.RData")
load("RData/m3_conf_post_wins.RData")
load("RData/m4_conf_post_wins.RData")
```

```{r}
load("RData/m1_conf_post_wins_52.RData")
load("RData/m2_conf_post_wins_52.RData")
load("RData/m2_conf_post_wins_104.RData")
load("RData/m2_conf_post_wins_156.RData")
```

```{r}
load("RData/m1_conf_post_wins_104.RData")
load("RData/m3_conf_post_wins_52.RData")
load("RData/m3_conf_post_wins_104.RData")
load("RData/m3_conf_post_wins_156.RData")
```

```{r}
load("RData/m1_conf_post_wins_156.RData")
load("RData/m4_conf_post_wins_52.RData")
load("RData/m4_conf_post_wins_104.RData")
load("RData/m4_conf_post_wins_156.RData")
```

----------------------------------------------------------------------
----------------------------------------------------------------------
ALL TRIALS
----------------------------------------------------------------------
----------------------------------------------------------------------


----------------------------------------------------------------------
Mean and SD
----------------------------------------------------------------------


Individual mean across all trials:
1S
```{r}
m1_conf_sub <- m1_conf_post_wins %>%
  group_by(subject) %>%
  mutate(confidence = as.numeric(confidence)) %>%
  filter(!is.na(confidence)) %>%
  summarize(mean_confidence = mean(confidence), sd_confidence = sd(confidence))

m1_conf_sub

save(m1_conf_sub, file = "RData/m1_conf_sub.RData")
```
2S
```{r}
m2_conf_sub <- m2_conf_post_wins %>%
  group_by(subject, state) %>%
  summarize(mean_confidence = mean(confidence), sd_confidence = sd(confidence))

m2_conf_sub

#save(m2_conf_sub, file = "RData/m2_conf_sub.RData")
```
```{r}
m2_conf_sub |> 
  ggplot(aes(x = state, y = mean_confidence)) +
  geom_jitter() 
```


```{r}
m2_conf_t.test <- t.test(mean_confidence ~ state, m2_conf_sub, paired = TRUE)
m2_conf_t.test
```




3S
```{r}
m3_conf_sub <- m3_conf_post_wins %>%
  group_by(subject, state) %>%
  mutate(confidence = as.numeric(confidence)) %>%
  filter(!is.na(confidence)) %>%
  summarize(mean_confidence = mean(confidence), sd_confidence = sd(confidence))

m3_conf_sub

save(m3_conf_sub, file = "RData/m3_conf_sub.RData")
```
4S
```{r}
m4_conf_sub <- m4_conf_post_wins %>%
  group_by(subject, state) %>%
  mutate(confidence = as.numeric(confidence)) %>%
  filter(!is.na(confidence)) %>%
  summarize(mean_confidence = mean(confidence), sd_confidence = sd(confidence))

m4_conf_sub

save(m4_conf_dist, file = "RData/m4_conf_sub.RData")
```


----------------------------------------------------------------------
State comparison
----------------------------------------------------------------------


M2:
```{r}
m2_conf_t.test <- t.test(mean_confidence ~ state, m2_conf_dist, paired = T)
m2_conf_t.test
```

```{r}
model <- lm(mean_confidence ~ state, m2_conf_dist)
residuals <- residuals(model)

shapiro.test(residuals)
bptest(model)
```


M3 (I don't know if this is good with dependant samples):

```{r}

```

```{r}
m3_conf_aov <- aov(mean_confidence ~ state + Error(subject / state), data = m3_conf_sub)

summary(m3_conf_aov)
#shapiro.test(m3_conf_aov$residuals)
```

```{r}
m3_conf_sub |> 
  ggplot(aes(x = state, y = mean_confidence)) +
 # geom_jitter() +
   stat_summary(
    fun = "mean",
    geom = "point",
    shape = 16,
    size = 3,
    color = "red"
  ) +
  stat_summary(
    fun.data = mean_cl_normal,
    geom = "errorbar",
    width = 0.2,
    color = "red"
  )
```


```{r}
m3_conf_aov_result <- Anova(m3_conf_aov, idata = m3_conf_dist, idesign = ~ subject, type = "III", white.adjust = "hc3")
m3_conf_aov_result
TukeyHSD(m3_conf_aov)
```

M4:
```{r}
m4_conf_aov <- aov(mean_confidence ~ state, data = m4_conf_dist)
m4_conf_aov
shapiro.test(m4_conf_aov$residuals)
```
```{r}
m4_conf_aov_result <- Anova(m4_conf_aov, idata = m4_conf_dist, idesign = ~ subject, type = "III", white.adjust = "hc3")
m4_conf_aov_result
TukeyHSD(m4_conf_aov)
```


