---
title: "hlmhmm metacognition seed selection and model comparison"
output: html_notebook
---


```{r}
library(reticulate)
use_condaenv("glmhmm")

source_python("python/glm_hmm.py")
```

```{python}
import numpy as np
import numpy.random as npr
import matplotlib.pyplot as plt
import ssm 
```

```{r}
library(tidyverse)
library(broom)
library(dplyr)
library(R.matlab)
library(cowplot)

list.files("R", full.names = TRUE) |> 
  walk(source)
```


```{r}
load("RData/glm_hmm1_seeds.RData")
load("RData/glm_hmm2_seeds.RData")
load("RData/glm_hmm3_seeds.RData")
```


Renames the states according to their values (so similar states between subjects can be identified)
```{r}
# glm_hmm1 <- glm_hmm1_seeds %>% 
#     mutate(fit = list(glm_hmm_extract_best(fit))) %>%
#     order_states_glm_hmm()
# 
# glm_hmm1
# 
# save(glm_hmm1, file = "RData/glm_hmm1.RData")
```



```{r}
glm_hmm2 <- glm_hmm2_seeds %>%
  mutate(fit = list(glm_hmm_extract_best(fit))) |> 
  select(-data) |> 
  unnest_wider(fit)

glm_hmm2_weights <- glm_hmm2 |> 
  select(subject, recovered_weights) |> 
  unnest(recovered_weights)

glm_hmm2_order <- glm_hmm2_weights |> 
   filter(coef == "V2") |> 
   group_by(subject) |> 
   arrange(desc(value), .by_group = TRUE) |> 
   mutate(ordered_state = paste0("S", row_number())) |> 
   select(subject, state, ordered_state)


glm_hmm2_posterior_probs <- glm_hmm2 |> 
  select(subject, posterior_probs) |> 
  unnest(posterior_probs)

glm_hmm2_posterior_wins <- glm_hmm2_posterior_probs |> 
  group_by(subject, trial) %>%
  filter(p == max(p)) %>%
  select(-p) |> 
  left_join(glm_hmm2_order) |> 
  select(-state) |> 
  rename(state = ordered_state) |> 
  left_join(data_trials, 
            by = join_by(subject, trial))


#save(glm_hmm2, file = "RData/glm_hmm2.RData")
```

```{r}

```

```{r}
# glm_hmm3 <- glm_hmm3_seeds %>%
#   mutate(fit = list(glm_hmm_extract_best(fit))) %>%
#   order_states_glm_hmm()
# 
# glm_hmm3
# 
# save(glm_hmm3, file = "RData/glm_hmm3.RData")
```

```{r}
# glm_hmm4 <- glm_hmm4_seeds %>%
#   mutate(fit = list(glm_hmm_extract_best(fit))) %>%
#   order_states_glm_hmm()
# 
# glm_hmm4
# 
# save(glm_hmm4, file = "RData/glm_hmm4.RData")
```

```{r}
load("RData/glm_hmm1.RData")
load("RData/glm_hmm2.RData")
load("RData/glm_hmm3.RData")
load("RData/glm_hmm4.RData")
```


---------------------------------------------------------------------
---------------------------------------------------------------------
MODEL COMPARISON 
---------------------------------------------------------------------
---------------------------------------------------------------------


liks de cada modelo
```{r}
liks_glm_hmm1 <- glm_hmm1_seeds %>% 
  mutate(fit = list(glm_hmm_extract_best(fit))) %>% 
  unnest_wider(fit) %>% 
  mutate(n = map(data, count)) %>% 
  unnest(n) %>% 
  select(subject, log_lik, n_par, n) %>% 
  mutate(model = "int-slo 1")

liks_glm_hmm2 <- glm_hmm2_seeds %>% 
  mutate(fit = list(glm_hmm_extract_best(fit))) %>% 
  unnest_wider(fit) %>% 
  mutate(n = map(data, count)) %>% 
  unnest(n) %>% 
  select(subject, log_lik, n_par, n) %>% 
  mutate(model = "int-slo 2")

liks_glm_hmm3 <- glm_hmm3_seeds %>%
  mutate(fit = list(glm_hmm_extract_best(fit))) %>%
  unnest_wider(fit) %>%
  mutate(n = map(data, count)) %>%
  unnest(n) %>%
  select(subject, log_lik, n_par, n) %>%
  mutate(model = "int-slo 3")
```

DL:
```{r}
liks_glm_hmm <- liks_glm_hmm1 |> 
  bind_rows(liks_glm_hmm2) |> 
  bind_rows(liks_glm_hmm3) |> 
  mutate(aic = -2 * log_lik + 2 *n_par)

save(liks_glm_hmm, file = "RData/liks_glm_hmm.RData")

liks_glm_hmm_best <- liks_glm_hmm |> 
  group_by(subject) |> 
  filter(aic == min(aic)) 

liks_glm_hmm_best |> 
  ungroup() |> 
  count(model)

save(liks_glm_hmm_best, file = "RData/liks_glm_hmm_best.RData")
```

